### ISSUE TITLE
Bootstrapping x86_64 cross toolchain

### ISSUE THREAD

**Issue by kxxt** [felixonmars/archriscv-packages#4353]
Because there's no package like x86_64-linux-gnu-glibc in Arch Linux's repo,
we must bootstrap from scratch.

## Build Order

Target linux api headers and binutils:

- [x] x86_64-linux-gnu-binutils(#4342)
- [x] x86_64-linux-gnu-linux-api-headers(#4343)

Build bare gcc to compile glibc stubs:

- [x] x86_64-linux-gnu-gcc-bootstrap(#4348)

Build glibc stubs with x86_64-linux-gnu-gcc-bootstrap

- [x] x86_64-linux-gnu-glibc-headers(#4349)

Build a minimal gcc with x86_64-linux-gnu-glibc-headers 

- [x] x86_64-linux-gnu-gcc(#4350)

Build full target glibc with the minimal gcc:

- [x] x86_64-linux-gnu-glibc(#4351)

Build full gcc now:

- [x] x86_64-linux-gnu-gcc (#4356)

Optionally build target glibc again with full gcc and then rebuild gcc: 

- [ ] x86_64-linux-gnu-glibc
- [ ] x86_64-linux-gnu-gcc
